AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for Step Functions to orchestrate Glue jobs and crawlers

Parameters:
  ProjectName:
    Type: String
    Default: retail-intelligence

Resources:
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-stepfunctions-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-sfn-glue-access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                  - glue:BatchStopJobRun
                  - glue:StartCrawler
                  - glue:GetCrawler
                Resource: "*"

Outputs:
  StepFunctionsRoleArn:
    Value: !GetAtt StepFunctionsRole.Arn
    Export:
      Name: !Sub "${ProjectName}-stepfunctions-role-arn"